# Generated by Django 4.2.28 on 2026-02-14 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='inwardlot',
            name='inward_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='processprogram',
            name='output_meters',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
