# Generated by Django 4.2.28 on 2026-02-14 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_updated_at_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gst_number', models.CharField(blank=True, help_text='GSTIN - leave blank if not applicable for this quality type', max_length=15, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo for PDF invoices', null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quality_type', models.OneToOneField(help_text='Quality type for which this company detail applies', on_delete=django.db.models.deletion.CASCADE, related_name='company_detail', to='inventory.qualitytype')),
            ],
            options={
                'verbose_name': 'Company Detail',
                'verbose_name_plural': 'Company Details',
                'ordering': ['quality_type__name'],
            },
        ),
    ]
