# Generated by Django 4.2.28 on 2026-02-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_companydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardlot',
            name='is_gstin_registered',
            field=models.BooleanField(default=False, help_text='Whether this lot is for a GSTIN-registered transaction'),
        ),
    ]
