# Generated by Django 4.2.28 on 2026-02-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inwardlot_is_gstin_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Outstanding', 'Outstanding'), ('Scrap', 'Scrap')], db_index=True, default='Draft', help_text='Current payment/billing status', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='sent_date',
            field=models.DateTimeField(blank=True, help_text='Date when bill was sent to party', null=True),
        ),
    ]
