# Generated by Django 4.2.28 on 2026-02-16 07:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_bill_payment_status_bill_sent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyQualityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_meter', models.DecimalField(decimal_places=2, help_text='Custom rate for this party-quality combination', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this pricing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_rates', to='inventory.party')),
                ('quality_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_rates', to='inventory.qualitytype')),
            ],
            options={
                'verbose_name': 'Party Quality Rate',
                'verbose_name_plural': 'Party Quality Rates',
                'db_table': 'party_quality_rates',
                'ordering': ['party__name', 'quality_type__name'],
                'indexes': [models.Index(fields=['party', 'quality_type'], name='party_quali_party_i_8abf3b_idx')],
                'unique_together': {('party', 'quality_type')},
            },
        ),
    ]
