# Generated by Django 4.2.28 on 2026-02-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='processprogram',
            name='challan_no',
            field=models.CharField(blank=True, db_index=True, help_text='Challan number for this program (optional, must be unique)', max_length=100, null=True, unique=True),
        ),
    ]
