# Generated by Django 4.2.28 on 2026-02-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_add_challan_no_to_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardlot',
            name='lr_number',
            field=models.CharField(blank=True, help_text='LR (Lorry Receipt) Number - can be duplicated across lots', max_length=100, null=True),
        ),
    ]
