# Generated by Django 4.2.28 on 2026-02-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inwardlot_lr_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processprogram',
            name='design_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
