# Generated by Django 4.2.28 on 2026-02-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_processprogram_design_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetail',
            options={'verbose_name': 'Company Detail', 'verbose_name_plural': 'Company Details'},
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='quality_type',
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GSTIN - leave blank if not applicable', max_length=15, null=True),
        ),
    ]
